apiVersion: v1
kind: Service
metadata:
  name: resource-backend-service
spec:
  selector:
    app: resource-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
